// Where Led is connected

// Which Port, PIN
#define PERIPHERAL_BASE 	(0x4000 0000UL)
#define AHB2RERIF_OFFSET 	(0x0800 0000UL)
#define AHB2RERIF_BASE      (PERIPHERAL_BASE + AHB2RERIF_OFFSET)

#define GPIOA_OFFSET		(0x0000UL)
#define GPIOA_BASE 			(AHB2RERIF_BASE+GPIOA_OFFSET)

